#!/usr/bin/env bash

export PATH="$PATH:/opt/homebrew/bin:/usr/local/bin"

if command -v swiftlint >/dev/null 2>&1
then
    swiftlint
else
    echo "warning: `swiftlint` command not found - See https://github.com/realm/SwiftLint#installation for installation instructions."
fi
