#!/usr/bin/env bash
set -euo pipefail

. "$(dirname "$0")/../Lib/request.sh"
. "$(dirname "$0")/../Lib/workflow.sh"

main() {
  start_workflow "SubflowsWorkflow"

  take_transition "GoToSubflow"
  take_transition "SimpleWorkflow"

  local subflow_id
  subflow_id="$(response_field '.transitionState.state.waitingWorkflow.workflowId')"

  assert_state "beforeSubflow"
  take_transition "StartA" "$subflow_id"
  take_transition "StartB" "$subflow_id"
  assert_state "beforeSubflow"
  take_transition "Finalize" "$subflow_id"

  assert_state "subflowFinished"
  take_transition "FinishAfterSubflow"

  echo "Finished Successfully"
}

main "$@"
