#!/usr/bin/env bash
set -euo pipefail

. "$(dirname "$0")/../Lib/request.sh"
. "$(dirname "$0")/../Lib/workflow.sh"

main() {
  start_workflow "WaitingWorkflow"

  take_transition "CreateMessageTemplateFile"
  assert_state "templateCreated"

  sleep 2
  assert_state "templateCreated"

  echo "Content" > "/tmp/MessageTemplate.md"
  sleep 2
  assert_state "messageReady"

  take_transition "SendMessage"
  echo "Finished Successfully"
}

main "$@"
