#!/usr/bin/env bash
set -euo pipefail

. "$(dirname "$0")/../Lib/request.sh"
. "$(dirname "$0")/../Lib/workflow.sh"

main() {
  start_workflow "AutomaticSimpleGitWorkflow"
  assert_finished
  echo "Finished Successfully"
}

main "$@"
