#!/usr/bin/env bash
set -euo pipefail

. "$(dirname "$0")/../Lib/request.sh"
. "$(dirname "$0")/../Lib/workflow.sh"

main() {
  start_workflow "SimpleGitWorkflow"

  take_transition "CreateTempWorkingDirectory"
  take_transition "InitialiseRepository"
  take_transition "WriteReadmeFile"
  take_transition "CommitChanges"
  take_transition "CleanWorkingFolder"

  assert_finished
  echo "Finished Successfully"
}

main "$@"
