#!/usr/bin/env bash
set -euo pipefail

. "$(dirname "$0")/../Lib/request.sh"
. "$(dirname "$0")/../Lib/workflow.sh"

main() {
  start_workflow "SimpleWorkflow"
  assert_exists

  take_transition "StartA"
  take_transition "StartB"
  take_transition "Finalize"

  assert_finished
  echo "Finished Successfully"
}

main "$@"
